// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_game.proto

package auth_game_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type A2GVerifyUser struct {
	//玩家guid
	PlayerGuid           string   `protobuf:"bytes,1,opt,name=playerGuid,proto3" json:"playerGuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *A2GVerifyUser) Reset()         { *m = A2GVerifyUser{} }
func (m *A2GVerifyUser) String() string { return proto.CompactTextString(m) }
func (*A2GVerifyUser) ProtoMessage()    {}
func (*A2GVerifyUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_239a2a4f3b618ff3, []int{0}
}

func (m *A2GVerifyUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_A2GVerifyUser.Unmarshal(m, b)
}
func (m *A2GVerifyUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_A2GVerifyUser.Marshal(b, m, deterministic)
}
func (m *A2GVerifyUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_A2GVerifyUser.Merge(m, src)
}
func (m *A2GVerifyUser) XXX_Size() int {
	return xxx_messageInfo_A2GVerifyUser.Size(m)
}
func (m *A2GVerifyUser) XXX_DiscardUnknown() {
	xxx_messageInfo_A2GVerifyUser.DiscardUnknown(m)
}

var xxx_messageInfo_A2GVerifyUser proto.InternalMessageInfo

func (m *A2GVerifyUser) GetPlayerGuid() string {
	if m != nil {
		return m.PlayerGuid
	}
	return ""
}

type G2CVerifyUser struct {
	//登陆状态
	LoginState           bool     `protobuf:"varint,1,opt,name=loginState,proto3" json:"loginState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2CVerifyUser) Reset()         { *m = G2CVerifyUser{} }
func (m *G2CVerifyUser) String() string { return proto.CompactTextString(m) }
func (*G2CVerifyUser) ProtoMessage()    {}
func (*G2CVerifyUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_239a2a4f3b618ff3, []int{1}
}

func (m *G2CVerifyUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2CVerifyUser.Unmarshal(m, b)
}
func (m *G2CVerifyUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2CVerifyUser.Marshal(b, m, deterministic)
}
func (m *G2CVerifyUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2CVerifyUser.Merge(m, src)
}
func (m *G2CVerifyUser) XXX_Size() int {
	return xxx_messageInfo_G2CVerifyUser.Size(m)
}
func (m *G2CVerifyUser) XXX_DiscardUnknown() {
	xxx_messageInfo_G2CVerifyUser.DiscardUnknown(m)
}

var xxx_messageInfo_G2CVerifyUser proto.InternalMessageInfo

func (m *G2CVerifyUser) GetLoginState() bool {
	if m != nil {
		return m.LoginState
	}
	return false
}

func init() {
	proto.RegisterType((*A2GVerifyUser)(nil), "auth_game_proto.a2g_verify_user")
	proto.RegisterType((*G2CVerifyUser)(nil), "auth_game_proto.g2c_verify_user")
}

func init() { proto.RegisterFile("auth_game.proto", fileDescriptor_239a2a4f3b618ff3) }

var fileDescriptor_239a2a4f3b618ff3 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x2c, 0x2d, 0xc9,
	0x88, 0x4f, 0x4f, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x42, 0x08, 0xc4, 0x83,
	0x05, 0x94, 0x0c, 0xb9, 0xf8, 0x13, 0x8d, 0xd2, 0xe3, 0xcb, 0x52, 0x8b, 0x32, 0xd3, 0x2a, 0xe3,
	0x4b, 0x8b, 0x53, 0x8b, 0x84, 0xe4, 0xb8, 0xb8, 0x0a, 0x72, 0x12, 0x2b, 0x53, 0x8b, 0xdc, 0x4b,
	0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x40, 0x5a, 0xd2, 0x8d, 0x92,
	0xd1, 0xb5, 0xe4, 0xe4, 0xa7, 0x67, 0xe6, 0x05, 0x97, 0x24, 0x96, 0xa4, 0x82, 0xb5, 0x70, 0x04,
	0x21, 0x89, 0x18, 0xa5, 0x73, 0x09, 0x86, 0x81, 0x95, 0x87, 0x16, 0xa7, 0x16, 0x05, 0xa7, 0x16,
	0x95, 0x65, 0x26, 0xa7, 0x0a, 0x05, 0x71, 0x71, 0x21, 0x04, 0x85, 0x14, 0xf4, 0xd0, 0x9c, 0xa6,
	0x87, 0xe6, 0x2e, 0x29, 0x4c, 0x15, 0x68, 0xce, 0x50, 0x62, 0x48, 0x62, 0x03, 0x4b, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x95, 0xd3, 0x19, 0xf9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerifyUserServiceClient is the client API for VerifyUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerifyUserServiceClient interface {
	VerifyUser(ctx context.Context, in *A2GVerifyUser, opts ...grpc.CallOption) (*G2CVerifyUser, error)
}

type verifyUserServiceClient struct {
	cc *grpc.ClientConn
}

func NewVerifyUserServiceClient(cc *grpc.ClientConn) VerifyUserServiceClient {
	return &verifyUserServiceClient{cc}
}

func (c *verifyUserServiceClient) VerifyUser(ctx context.Context, in *A2GVerifyUser, opts ...grpc.CallOption) (*G2CVerifyUser, error) {
	out := new(G2CVerifyUser)
	err := c.cc.Invoke(ctx, "/auth_game_proto.VerifyUserService/VerifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyUserServiceServer is the server API for VerifyUserService service.
type VerifyUserServiceServer interface {
	VerifyUser(context.Context, *A2GVerifyUser) (*G2CVerifyUser, error)
}

// UnimplementedVerifyUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVerifyUserServiceServer struct {
}

func (*UnimplementedVerifyUserServiceServer) VerifyUser(ctx context.Context, req *A2GVerifyUser) (*G2CVerifyUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyUser not implemented")
}

func RegisterVerifyUserServiceServer(s *grpc.Server, srv VerifyUserServiceServer) {
	s.RegisterService(&_VerifyUserService_serviceDesc, srv)
}

func _VerifyUserService_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(A2GVerifyUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyUserServiceServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_game_proto.VerifyUserService/VerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyUserServiceServer).VerifyUser(ctx, req.(*A2GVerifyUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _VerifyUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth_game_proto.VerifyUserService",
	HandlerType: (*VerifyUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyUser",
			Handler:    _VerifyUserService_VerifyUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_game.proto",
}
