// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inside/r_game_auth.proto

package inside

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//向auth服务器注册
type RGameAuthRegisterRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Guid                 uint64   `protobuf:"varint,3,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthRegisterRequest) Reset()         { *m = RGameAuthRegisterRequest{} }
func (m *RGameAuthRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RGameAuthRegisterRequest) ProtoMessage()    {}
func (*RGameAuthRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{0}
}

func (m *RGameAuthRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthRegisterRequest.Unmarshal(m, b)
}
func (m *RGameAuthRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthRegisterRequest.Marshal(b, m, deterministic)
}
func (m *RGameAuthRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthRegisterRequest.Merge(m, src)
}
func (m *RGameAuthRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RGameAuthRegisterRequest.Size(m)
}
func (m *RGameAuthRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthRegisterRequest proto.InternalMessageInfo

func (m *RGameAuthRegisterRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RGameAuthRegisterRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RGameAuthRegisterRequest) GetGuid() uint64 {
	if m != nil {
		return m.Guid
	}
	return 0
}

//向服务器定时发送ping,保证存活
type RGameAuthRegisterCallback struct {
	Guid                 uint64   `protobuf:"varint,1,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthRegisterCallback) Reset()         { *m = RGameAuthRegisterCallback{} }
func (m *RGameAuthRegisterCallback) String() string { return proto.CompactTextString(m) }
func (*RGameAuthRegisterCallback) ProtoMessage()    {}
func (*RGameAuthRegisterCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{1}
}

func (m *RGameAuthRegisterCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthRegisterCallback.Unmarshal(m, b)
}
func (m *RGameAuthRegisterCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthRegisterCallback.Marshal(b, m, deterministic)
}
func (m *RGameAuthRegisterCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthRegisterCallback.Merge(m, src)
}
func (m *RGameAuthRegisterCallback) XXX_Size() int {
	return xxx_messageInfo_RGameAuthRegisterCallback.Size(m)
}
func (m *RGameAuthRegisterCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthRegisterCallback.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthRegisterCallback proto.InternalMessageInfo

func (m *RGameAuthRegisterCallback) GetGuid() uint64 {
	if m != nil {
		return m.Guid
	}
	return 0
}

//ping
type RGameAuthPingRequest struct {
	Pid                  uint64   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthPingRequest) Reset()         { *m = RGameAuthPingRequest{} }
func (m *RGameAuthPingRequest) String() string { return proto.CompactTextString(m) }
func (*RGameAuthPingRequest) ProtoMessage()    {}
func (*RGameAuthPingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{2}
}

func (m *RGameAuthPingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthPingRequest.Unmarshal(m, b)
}
func (m *RGameAuthPingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthPingRequest.Marshal(b, m, deterministic)
}
func (m *RGameAuthPingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthPingRequest.Merge(m, src)
}
func (m *RGameAuthPingRequest) XXX_Size() int {
	return xxx_messageInfo_RGameAuthPingRequest.Size(m)
}
func (m *RGameAuthPingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthPingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthPingRequest proto.InternalMessageInfo

func (m *RGameAuthPingRequest) GetPid() uint64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

//ping
type RGameAuthPingCallback struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthPingCallback) Reset()         { *m = RGameAuthPingCallback{} }
func (m *RGameAuthPingCallback) String() string { return proto.CompactTextString(m) }
func (*RGameAuthPingCallback) ProtoMessage()    {}
func (*RGameAuthPingCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{3}
}

func (m *RGameAuthPingCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthPingCallback.Unmarshal(m, b)
}
func (m *RGameAuthPingCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthPingCallback.Marshal(b, m, deterministic)
}
func (m *RGameAuthPingCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthPingCallback.Merge(m, src)
}
func (m *RGameAuthPingCallback) XXX_Size() int {
	return xxx_messageInfo_RGameAuthPingCallback.Size(m)
}
func (m *RGameAuthPingCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthPingCallback.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthPingCallback proto.InternalMessageInfo

//login
type RGameAuthLoginRequest struct {
	PlayerGuid           uint64   `protobuf:"varint,1,opt,name=playerGuid,proto3" json:"playerGuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthLoginRequest) Reset()         { *m = RGameAuthLoginRequest{} }
func (m *RGameAuthLoginRequest) String() string { return proto.CompactTextString(m) }
func (*RGameAuthLoginRequest) ProtoMessage()    {}
func (*RGameAuthLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{4}
}

func (m *RGameAuthLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthLoginRequest.Unmarshal(m, b)
}
func (m *RGameAuthLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthLoginRequest.Marshal(b, m, deterministic)
}
func (m *RGameAuthLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthLoginRequest.Merge(m, src)
}
func (m *RGameAuthLoginRequest) XXX_Size() int {
	return xxx_messageInfo_RGameAuthLoginRequest.Size(m)
}
func (m *RGameAuthLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthLoginRequest proto.InternalMessageInfo

func (m *RGameAuthLoginRequest) GetPlayerGuid() uint64 {
	if m != nil {
		return m.PlayerGuid
	}
	return 0
}

//login
type RGameAuthLoginCallback struct {
	State                bool     `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Guid                 uint64   `protobuf:"varint,2,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthLoginCallback) Reset()         { *m = RGameAuthLoginCallback{} }
func (m *RGameAuthLoginCallback) String() string { return proto.CompactTextString(m) }
func (*RGameAuthLoginCallback) ProtoMessage()    {}
func (*RGameAuthLoginCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{5}
}

func (m *RGameAuthLoginCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthLoginCallback.Unmarshal(m, b)
}
func (m *RGameAuthLoginCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthLoginCallback.Marshal(b, m, deterministic)
}
func (m *RGameAuthLoginCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthLoginCallback.Merge(m, src)
}
func (m *RGameAuthLoginCallback) XXX_Size() int {
	return xxx_messageInfo_RGameAuthLoginCallback.Size(m)
}
func (m *RGameAuthLoginCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthLoginCallback.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthLoginCallback proto.InternalMessageInfo

func (m *RGameAuthLoginCallback) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

func (m *RGameAuthLoginCallback) GetGuid() uint64 {
	if m != nil {
		return m.Guid
	}
	return 0
}

func init() {
	proto.RegisterType((*RGameAuthRegisterRequest)(nil), "inside.r_game_auth_register_request")
	proto.RegisterType((*RGameAuthRegisterCallback)(nil), "inside.r_game_auth_register_callback")
	proto.RegisterType((*RGameAuthPingRequest)(nil), "inside.r_game_auth_ping_request")
	proto.RegisterType((*RGameAuthPingCallback)(nil), "inside.r_game_auth_ping_callback")
	proto.RegisterType((*RGameAuthLoginRequest)(nil), "inside.r_game_auth_login_request")
	proto.RegisterType((*RGameAuthLoginCallback)(nil), "inside.r_game_auth_login_callback")
}

func init() { proto.RegisterFile("inside/r_game_auth.proto", fileDescriptor_750fdc613fd47738) }

var fileDescriptor_750fdc613fd47738 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbd, 0x4f, 0x04, 0x21,
	0x10, 0xc5, 0xc3, 0x7d, 0x45, 0xa7, 0x32, 0x1b, 0x0b, 0xfc, 0xcc, 0x86, 0x6a, 0x0b, 0xa3, 0xc5,
	0x95, 0xf6, 0xda, 0x53, 0xda, 0x10, 0xee, 0x6e, 0xc2, 0x11, 0x71, 0x41, 0x98, 0x2d, 0xfc, 0xef,
	0xcd, 0x72, 0x91, 0xc5, 0xec, 0x75, 0x8f, 0x79, 0xf3, 0x7b, 0x79, 0x03, 0x70, 0xdb, 0x27, 0x7b,
	0xc0, 0x97, 0xa8, 0x8c, 0xfe, 0x42, 0xa5, 0x07, 0x3a, 0x3e, 0x87, 0xe8, 0xc9, 0x37, 0x9b, 0x93,
	0x23, 0x3e, 0xe0, 0xbe, 0x32, 0x55, 0x44, 0x63, 0x13, 0x61, 0x54, 0x11, 0xbf, 0x07, 0x4c, 0xd4,
	0x34, 0xb0, 0x3a, 0xfa, 0x44, 0x9c, 0xb5, 0xac, 0xbb, 0x94, 0x59, 0x8f, 0xb3, 0xe0, 0x23, 0xf1,
	0x45, 0xcb, 0xba, 0xb5, 0xcc, 0x7a, 0x9c, 0x99, 0xc1, 0x1e, 0xf8, 0xb2, 0x65, 0xdd, 0x4a, 0x66,
	0x2d, 0xb6, 0xf0, 0x70, 0x36, 0x7b, 0xaf, 0x9d, 0xdb, 0xe9, 0xfd, 0x67, 0x81, 0x58, 0x05, 0x3d,
	0x01, 0xaf, 0xa1, 0x60, 0x7b, 0x53, 0xca, 0x5c, 0xc1, 0x32, 0x94, 0xf5, 0x51, 0x8a, 0x3b, 0xb8,
	0x99, 0x6d, 0xff, 0xc5, 0x8b, 0xd7, 0xff, 0xa6, 0xf3, 0xc6, 0xf6, 0x25, 0xeb, 0x11, 0x20, 0x38,
	0xfd, 0x83, 0xf1, 0x7d, 0x6a, 0x50, 0x4d, 0xc4, 0x1b, 0xdc, 0xce, 0xe1, 0xd2, 0xfc, 0x1a, 0xd6,
	0x89, 0x34, 0x61, 0x06, 0x2f, 0xe4, 0xe9, 0x51, 0xee, 0x59, 0x4c, 0xf7, 0xec, 0x36, 0xf9, 0xbf,
	0xb7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x00, 0xd0, 0xa9, 0x8b, 0x01, 0x00, 0x00,
}
