// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inside/r_game_auth.proto

package inside

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//向auth服务器注册
type RGameAuthRegisterRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthRegisterRequest) Reset()         { *m = RGameAuthRegisterRequest{} }
func (m *RGameAuthRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RGameAuthRegisterRequest) ProtoMessage()    {}
func (*RGameAuthRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{0}
}

func (m *RGameAuthRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthRegisterRequest.Unmarshal(m, b)
}
func (m *RGameAuthRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthRegisterRequest.Marshal(b, m, deterministic)
}
func (m *RGameAuthRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthRegisterRequest.Merge(m, src)
}
func (m *RGameAuthRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RGameAuthRegisterRequest.Size(m)
}
func (m *RGameAuthRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthRegisterRequest proto.InternalMessageInfo

func (m *RGameAuthRegisterRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RGameAuthRegisterRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

//向服务器定时发送ping,保证存活
type RGameAuthRegisterCallback struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthRegisterCallback) Reset()         { *m = RGameAuthRegisterCallback{} }
func (m *RGameAuthRegisterCallback) String() string { return proto.CompactTextString(m) }
func (*RGameAuthRegisterCallback) ProtoMessage()    {}
func (*RGameAuthRegisterCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{1}
}

func (m *RGameAuthRegisterCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthRegisterCallback.Unmarshal(m, b)
}
func (m *RGameAuthRegisterCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthRegisterCallback.Marshal(b, m, deterministic)
}
func (m *RGameAuthRegisterCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthRegisterCallback.Merge(m, src)
}
func (m *RGameAuthRegisterCallback) XXX_Size() int {
	return xxx_messageInfo_RGameAuthRegisterCallback.Size(m)
}
func (m *RGameAuthRegisterCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthRegisterCallback.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthRegisterCallback proto.InternalMessageInfo

//ping
type RGameAuthPingRequest struct {
	Pid                  string   `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthPingRequest) Reset()         { *m = RGameAuthPingRequest{} }
func (m *RGameAuthPingRequest) String() string { return proto.CompactTextString(m) }
func (*RGameAuthPingRequest) ProtoMessage()    {}
func (*RGameAuthPingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{2}
}

func (m *RGameAuthPingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthPingRequest.Unmarshal(m, b)
}
func (m *RGameAuthPingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthPingRequest.Marshal(b, m, deterministic)
}
func (m *RGameAuthPingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthPingRequest.Merge(m, src)
}
func (m *RGameAuthPingRequest) XXX_Size() int {
	return xxx_messageInfo_RGameAuthPingRequest.Size(m)
}
func (m *RGameAuthPingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthPingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthPingRequest proto.InternalMessageInfo

func (m *RGameAuthPingRequest) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

//ping
type RGameAuthPingCallback struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RGameAuthPingCallback) Reset()         { *m = RGameAuthPingCallback{} }
func (m *RGameAuthPingCallback) String() string { return proto.CompactTextString(m) }
func (*RGameAuthPingCallback) ProtoMessage()    {}
func (*RGameAuthPingCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_750fdc613fd47738, []int{3}
}

func (m *RGameAuthPingCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RGameAuthPingCallback.Unmarshal(m, b)
}
func (m *RGameAuthPingCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RGameAuthPingCallback.Marshal(b, m, deterministic)
}
func (m *RGameAuthPingCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RGameAuthPingCallback.Merge(m, src)
}
func (m *RGameAuthPingCallback) XXX_Size() int {
	return xxx_messageInfo_RGameAuthPingCallback.Size(m)
}
func (m *RGameAuthPingCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_RGameAuthPingCallback.DiscardUnknown(m)
}

var xxx_messageInfo_RGameAuthPingCallback proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RGameAuthRegisterRequest)(nil), "inside.r_game_auth_register_request")
	proto.RegisterType((*RGameAuthRegisterCallback)(nil), "inside.r_game_auth_register_callback")
	proto.RegisterType((*RGameAuthPingRequest)(nil), "inside.r_game_auth_ping_request")
	proto.RegisterType((*RGameAuthPingCallback)(nil), "inside.r_game_auth_ping_callback")
}

func init() { proto.RegisterFile("inside/r_game_auth.proto", fileDescriptor_750fdc613fd47738) }

var fileDescriptor_750fdc613fd47738 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc8, 0xcc, 0x2b, 0xce,
	0x4c, 0x49, 0xd5, 0x2f, 0x8a, 0x4f, 0x4f, 0xcc, 0x4d, 0x8d, 0x4f, 0x2c, 0x2d, 0xc9, 0xd0, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xc8, 0x28, 0xb9, 0x71, 0xc9, 0x20, 0x49, 0xc6, 0x17,
	0xa5, 0xa6, 0x67, 0x16, 0x97, 0xa4, 0x16, 0xc5, 0x17, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0x09, 0x71, 0xb1, 0x64, 0xe4, 0x17, 0x97, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x20, 0xb1, 0x82, 0xfc, 0xa2, 0x12, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30, 0x5b, 0x49,
	0x9e, 0x4b, 0x16, 0xab, 0x39, 0xc9, 0x89, 0x39, 0x39, 0x49, 0x89, 0xc9, 0xd9, 0x4a, 0x3a, 0x5c,
	0x12, 0xc8, 0x0a, 0x0a, 0x32, 0xf3, 0xd2, 0xe1, 0x96, 0x08, 0x70, 0x31, 0x17, 0x64, 0xa6, 0x40,
	0xed, 0x00, 0x31, 0x95, 0xa4, 0xb9, 0x24, 0x31, 0x54, 0xc3, 0x8c, 0x4a, 0x62, 0x03, 0x7b, 0xc1,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xab, 0xfc, 0xbc, 0xba, 0xde, 0x00, 0x00, 0x00,
}
